# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50f42a018d7f69a8f0cadb86a802433b5bcd18fc3e847b81d671a078b1656ef1da50a5bb28e6e05e9882a7df241644e7584af3351422791cc68947b07c0d421d

test:
  secret_key_base: 6b7dcaa561c59078d152365a24fa1c8e140c7456240ee8e9ae224499b5c908cb93125e2fd5f899f5dc2c4ded0154256c6c598a5cfcac919d50d24c586c50cbce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
